language: ruby
rvm:
- 2.1
install: gem install jekyll
script: jekyll build

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
