# Site settings
title: Kevin Law
email: mail@kevinlaw.info
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Kevin Law
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.kevinlaw.info" # the base hostname & protocol for your site
twitter_username: thatarchguy
github_username:  thatarchguy
permalink: /blog/:title.html
plugins: [redcarpet, jekyll-gist]
highlighter: Rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
